# Generated by Django 3.0.5 on 2020-04-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creationDate', models.DateField(verbose_name='Created on ')),
                ('imagePath', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mainQuestion', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('publicationDate', models.DateField(verbose_name='Published on ')),
                ('quizImagePath', models.CharField(default='/images/', max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('questionWorth', models.IntegerField(default=1)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('option5', models.CharField(max_length=50)),
                ('option1Worth', models.IntegerField(default=1)),
                ('option2Worth', models.IntegerField(default=0)),
                ('option3Worth', models.IntegerField(default=0)),
                ('option4Worth', models.IntegerField(default=0)),
                ('option5Worth', models.IntegerField(default=0)),
                ('option1img', models.CharField(default='/images/', max_length=250)),
                ('option2img', models.CharField(default='/images/', max_length=250)),
                ('option3img', models.CharField(default='/images/', max_length=250)),
                ('option4img', models.CharField(default='/images/', max_length=250)),
                ('option5img', models.CharField(default='/images/', max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
