# Generated by Django 3.0.5 on 2020-04-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='imagePath',
            field=models.CharField(default='imageurl', max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
