# Generated by Django 3.0.5 on 2020-04-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200421_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='isTest',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result1img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result2img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result3img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result4img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result5img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result6img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result7img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result8img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='result9img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3Worth',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4Worth',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4img',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='option5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='option5Worth',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option5img',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
