# Generated by Django 3.0.5 on 2020-04-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200423_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuizViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
